[package]
name = "rustylisp"
version = "0.1.0"
edition = "2021"

[dependencies]
pretty_env_logger = "0.5.0"
log = "0.4.0"
strum = "0.26.3"
strum_macros = "0.26.4"
clap = { version = "4.5.31", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.3"
